import React, { useState } from 'react';
import { read, utils } from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import DejaVuSans from './fonts/DejaVuSans-normal'; // Import de la police

function GhomalaCalendarApp() {
  const [calendarData, setCalendarData] = useState([]);

  // Handle CSV file upload
  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const data = new Uint8Array(e.target.result);
        const workbook = read(data, { type: 'array' });
        const sheetName = workbook.SheetNames[0];
        const sheet = workbook.Sheets[sheetName];
        const jsonData = utils.sheet_to_json(sheet);
        setCalendarData(jsonData);
      };
      reader.readAsArrayBuffer(file);
    }
  };

  // Generate PDF
  const generatePDF = () => {
    const doc = new jsPDF();

    // Ajouter la police personnalisée
    doc.addFileToVFS('DejaVuSans-normal.ttf', DejaVuSans);
    doc.addFont('DejaVuSans-normal.ttf', 'DejaVuSans', 'normal');
    doc.setFont('DejaVuSans');

    doc.text('Calendrier 2025 en Ghomala', 14, 20);
    doc.setFontSize(12);
    doc.text('Generated by Ghomala Calendar App', 14, 28);

    const tableData = calendarData.map((row) => [
      row['Date'],
      row['Day(Eng)'],
      row['Day(Ghomala)'],
    ]);

    doc.autoTable({
      head: [['Date', 'Jour (Anglais)', 'Jour (Ghomala)']],
      body: tableData,
      startY: 40,
    });

    doc.save('Calendrier_2025_Ghomala.pdf');
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
      <h1>Générateur de Calendrier 2025 en Ghomala</h1>
      <input
        type="file"
        accept=".csv"
        onChange={handleFileUpload}
        style={{ marginBottom: '20px' }}
      />
      {calendarData.length > 0 && (
        <div>
          <button
            onClick={generatePDF}
            style={{
              backgroundColor: '#4CAF50',
              color: 'white',
              padding: '10px 20px',
              border: 'none',
              cursor: 'pointer',
              fontSize: '16px',
            }}
          >
            Télécharger le PDF
          </button>
          <table
            style={{
              marginTop: '20px',
              borderCollapse: 'collapse',
              width: '100%',
            }}
          >
            <thead>
              <tr>
                <th style={{ border: '1px solid #ddd', padding: '8px' }}>Date</th>
                <th style={{ border: '1px solid #ddd', padding: '8px' }}>Jour (Anglais)</th>
                <th style={{ border: '1px solid #ddd', padding: '8px' }}>Jour (Ghomala)</th>
              </tr>
            </thead>
            <tbody>
              {calendarData.map((row, index) => (
                <tr key={index}>
                  <td style={{ border: '1px solid #ddd', padding: '8px' }}>{row['Date']}</td>
                  <td style={{ border: '1px solid #ddd', padding: '8px' }}>{row['Day(Eng)']}</td>
                  <td style={{ border: '1px solid #ddd', padding: '8px' }}>{row['Day(Ghomala)']}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}


export default GhomalaCalendarApp;